import '@/app/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full overflow-auto bg-[#b2b2b2]">
      <body className={inter.className}>
        <div className="h-full overflow-auto bg-[#ffffff]">
        {children}
        </div>
        </body>
    </html>
  )
}